const businesses=[['Corner Café','Hospitality',5000,450,'A reliable neighborhood cash machine.'],['Swift Logistics','Transport',18000,1400,'Move goods between cities.'],['Nova Energy','Energy',75000,7200,'High growth, high ambition.'],['Titan Motors','Automotive',220000,23000,'Build the next global mobility empire.'],['Skyline Bank','Finance',600000,72000,'Own a piece of the financial world.'],['Orbit Telecom','Technology',1500000,210000,'Connect millions of customers.']];
const countries=[['Nigeria','🇳🇬',1.0],['United Kingdom','🇬🇧',1.25],['United States','🇺🇸',1.55],['Japan','🇯🇵',1.35],['UAE','🇦🇪',1.45],['Singapore','🇸🇬',1.5]];
const stocks=[['NOVA','Nova Energy',84.20,.072],['TITN','Titan Motors',142.50,-.031],['ORBT','Orbit Telecom',218.70,.114],['SKY','Skyline Bank',96.40,.024]];
const ranks=['ApexKing','MidasOne','CapitalWolf','GlobalTycoon','MoneyMind','You'];
let state=JSON.parse(localStorage.getItem('billionaire_state')||'null')||{cash:25000,gems:120,net:25000,level:1,xp:0,owned:[],country:'Nigeria',staff:0,stocks:{},properties:0,day:new Date().toDateString(),claimed:false};
let currentUser=localStorage.getItem('billionaire_user')||'';
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d}
async function sync(){if(!currentUser)return;try{const d=await api('/api/save',{method:'POST',body:JSON.stringify({username:currentUser,...state})});state={...state,...d.player};localStorage.setItem('billionaire_state',JSON.stringify(state))}catch(e){console.warn(e)}}
async function loginOrRegister(){const u=prompt('Choose a username (3+ characters):',currentUser||'');if(!u)return;const pw=prompt('Choose a password (6+ characters):');if(!pw)return;try{let d;try{d=await api('/api/login',{method:'POST',body:JSON.stringify({username:u,password:pw})})}catch{d=await api('/api/register',{method:'POST',body:JSON.stringify({username:u,password:pw})})}currentUser=u;localStorage.setItem('billionaire_user',u);state={...state,...d.player};save();toast(`Signed in as ${u}`);render('dashboard')}catch(e){toast(e.message)}}
if(state.day!==new Date().toDateString()){state.day=new Date().toDateString();state.claimed=false;state.cash+=1000;save()}
function save(){state.net=state.cash+state.owned.reduce((s,i)=>s+i.value,0)+state.properties*25000;localStorage.setItem('billionaire_state',JSON.stringify(state));sync()}
function money(n){return '$'+Math.round(n).toLocaleString()}
function toast(t){const e=document.querySelector('.toast');e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2200)}
function buy(i){const b=businesses[i];if(state.cash<b[2])return toast('Not enough cash. Grow your empire first.');state.cash-=b[2];state.owned.push({name:b[0],value:b[2],income:b[3]});state.xp+=20;level();save();toast(`${b[0]} acquired!`);render('businesses')}
function level(){while(state.xp>=state.level*100){state.xp-=state.level*100;state.level++;state.gems+=25;toast(`Level ${state.level} reached! +25 💎`)}}
function collect(){let inc=state.owned.reduce((s,i)=>s+i.income,0)*(1+state.staff*.08);state.cash+=inc;state.xp+=10;level();save();toast(`Collected ${money(inc)} business income.`);render('dashboard')}
function claim(){if(state.claimed)return toast('Daily reward already claimed.');state.claimed=true;state.cash+=2500;state.gems+=15;state.xp+=15;level();save();toast('Daily reward: $2,500 + 15 💎');render('dashboard')}
function hire(){const cost=3000+state.staff*1500;if(state.cash<cost)return toast('Not enough cash to hire.');state.cash-=cost;state.staff++;save();toast('Manager hired. Income boosted.');render('staff')}
function property(){const cost=25000+state.properties*20000;if(state.cash<cost)return toast('Not enough cash for property.');state.cash-=cost;state.properties++;state.xp+=30;level();save();toast('Property purchased!');render('properties')}
function trade(sym){const s=stocks.find(x=>x[0]===sym);const qty=1;if(state.cash<s[2])return toast('Not enough cash to buy this share.');state.cash-=s[2];state.stocks[sym]=(state.stocks[sym]||0)+qty;save();toast(`Bought 1 ${sym} share.`);render('stocks')}
function sell(sym){const s=stocks.find(x=>x[0]===sym);if(!(state.stocks[sym]>0))return toast('You do not own this stock.');state.stocks[sym]--;state.cash+=s[2];save();toast(`Sold 1 ${sym} share.`);render('stocks')}
function expand(c){const x=countries.find(x=>x[0]===c);if(state.country===c)return toast('Already operating here.');const cost=10000*x[2];if(state.cash<cost)return toast(`Expansion costs ${money(cost)}.`);state.cash-=cost;state.country=c;state.xp+=50;level();save();toast(`Expanded into ${c}!`);render('global')}
function nav(tab){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render(tab)}
function render(tab='dashboard'){
const app=document.querySelector('#app');
app.innerHTML=`<div class="shell"><header class="top"><div class="brand">THE <span>BILLIONAIRE</span></div><div><div class="wealth">${money(state.cash)}</div><div class="muted">Level ${state.level} · 💎 ${state.gems}</div></div><button class="btn alt" onclick="loginOrRegister()">${currentUser?'👤 '+currentUser:'Sign in'}</button></header><nav class="nav">${['dashboard','businesses','stocks','properties','staff','global','leaderboard'].map(t=>`<button data-tab="${t}" onclick="nav('${t}')">${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</nav><main class="main" id="content"></main><div class="toast"></div></div>`;
document.querySelector(`[data-tab="${tab}"]`).classList.add('active');
const c=document.querySelector('#content');
if(tab==='dashboard')c.innerHTML=dashboard();
if(tab==='businesses')c.innerHTML=businessesPage();
if(tab==='stocks')c.innerHTML=stocksPage();
if(tab==='properties')c.innerHTML=propertiesPage();
if(tab==='staff')c.innerHTML=staffPage();
if(tab==='global')c.innerHTML=globalPage();
if(tab==='leaderboard')c.innerHTML=leaderboardPage();
}
function dashboard(){const inc=state.owned.reduce((s,i)=>s+i.income,0)*(1+state.staff*.08);return `<section class="hero"><div class="card"><div class="eyebrow">Global wealth simulator</div><div class="h1">Build the empire.<br>Become <span style="color:var(--gold)">the billionaire.</span></div><p class="sub">Start with limited capital, make smart deals, hire the right people and expand across the world. Your goal: become #1.</p><div class="actions"><button class="btn" onclick="collect()">Collect income · ${money(inc)}</button><button class="btn alt" onclick="claim()">🎁 Daily reward</button></div></div><div class="card"><div class="eyebrow">Your empire</div><h2>${money(state.net)}</h2><p class="muted">Net worth</p><div class="bar"><i style="width:${Math.min(100,state.xp/(state.level*100)*100)}%"></i></div><p class="muted">Level ${state.level} · ${state.xp}/${state.level*100} XP</p><hr style="border-color:var(--line);border-width:1px 0 0"><p>🌍 ${state.country}</p><p>🏢 ${state.owned.length} businesses</p><p>👔 ${state.staff} managers</p><p>🏠 ${state.properties} properties</p></div></section><section class="section"><h2>Empire snapshot</h2><div class="statgrid"><div class="card stat"><div class="muted">Cash</div><div class="num">${money(state.cash)}</div></div><div class="card stat"><div class="muted">Businesses</div><div class="num">${state.owned.length}</div></div><div class="card stat"><div class="muted">Managers</div><div class="num">${state.staff}</div></div><div class="card stat"><div class="muted">Properties</div><div class="num">${state.properties}</div></div></div></section><section class="section"><h2>Today's challenge</h2><div class="card reward"><div><b>First acquisition</b><div class="muted">Buy your first business and earn 50 XP.</div></div><span class="pill">${state.owned.length?'COMPLETED':'+50 XP'}</span></div></section>`}
function businessesPage(){return `<section><div class="eyebrow">Acquire & scale</div><h1>Businesses</h1><p class="sub">Every business generates cash over time. Reinvest profits to unlock larger companies.</p><div class="business-grid">${businesses.map((b,i)=>`<div class="card business"><span class="pill">${b[1]}</span><h3>${b[0]}</h3><p class="muted">${b[4]}</p><div class="price">${money(b[2])}</div><div class="muted">Income ${money(b[3])}/cycle</div><div class="actions"><button class="btn" onclick="buy(${i})">Acquire</button></div></div>`).join('')}</div></section>`}
function stocksPage(){return `<section><div class="eyebrow">Markets</div><h1>Global Stocks</h1><p class="sub">Buy and sell simulated shares. Prices are designed for gameplay and change as your empire progresses.</p><div class="grid">${stocks.map(s=>`<div class="card"><span class="pill">${s[0]}</span><h3>${s[1]}</h3><div class="price">${money(s[2])}</div><p style="color:${s[3]>=0?'var(--green)':'var(--red)'}">${s[3]>=0?'+':''}${(s[3]*100).toFixed(1)}% today</p><p class="muted">Owned: ${state.stocks[s[0]]||0}</p><div class="actions"><button class="btn" onclick="trade('${s[0]}')">Buy</button><button class="btn alt" onclick="sell('${s[0]}')">Sell</button></div></div>`).join('')}</div></section>`}
function propertiesPage(){return `<section><div class="eyebrow">Real estate</div><h1>Properties</h1><p class="sub">Convert cash into long-term assets. Each property adds $25,000 to net worth.</p><div class="card"><h2>Premium city property</h2><p class="muted">Purchase #${state.properties+1}</p><div class="price">${money(25000+state.properties*20000)}</div><button class="btn" onclick="property()">Purchase property</button></div></section>`}
function staffPage(){const cost=3000+state.staff*1500;return `<section><div class="eyebrow">People & management</div><h1>Hire your team</h1><p class="sub">Managers increase business income by 8% each. Build a leadership team as your empire grows.</p><div class="card"><h2>Executive Manager</h2><p>Current managers: ${state.staff}</p><p class="muted">Next hire: ${money(cost)} · +8% business income</p><button class="btn" onclick="hire()">Hire manager</button></div></section>`}
function globalPage(){return `<section><div class="eyebrow">International expansion</div><h1>Go global</h1><p class="sub">Expand your headquarters into new markets and chase worldwide dominance.</p><div class="grid">${countries.map(x=>`<div class="card"><div style="font-size:32px">${x[1]}</div><h3>${x[0]}</h3><p class="muted">Expansion cost: ${money(10000*x[2])}</p><span class="pill">${state.country===x[0]?'ACTIVE':'LOCKED'}</span><div class="actions"><button class="btn" onclick="expand('${x[0]}')">Expand</button></div></div>`).join('')}</div></section>`}
async function onlineLeaderboard(){try{const d=await api('/api/leaderboard');return d.leaderboard}catch{return []}}
function leaderboardPage(){const score=state.net;const rows=ranks.map((n,i)=>({n,score:i===5?score:[1200000000,870000000,640000000,410000000,220000000][i]})).sort((a,b)=>b.score-a.score);setTimeout(async()=>{const list=await onlineLeaderboard();const table=document.querySelector('.online-table');if(table&&list.length)table.innerHTML=list.map((r,i)=>`<tr><td>#${i+1}</td><td>${r.username}</td><td>${money(r.net)}</td></tr>`).join('')},100);return `<section><div class="eyebrow">World rankings</div><h1>Billionaire Leaderboard</h1><p class="sub">Compete against global tycoons. Your rank is calculated from total net worth.</p><div class="card"><table class="table"><thead><tr><th>Rank</th><th>Player</th><th>Net worth</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td class="rank">#${i+1}</td><td>${r.n}${r.n==='You'?' 👑':''}</td><td>${money(r.score)}</td></tr>`).join('')}</tbody></table></div><h2 style="margin-top:24px">Online players</h2><div class="card"><table class="table"><thead><tr><th>Rank</th><th>Player</th><th>Net worth</th></tr></thead><tbody class="online-table"><tr><td colspan="3">Loading…</td></tr></tbody></table></div></section>`}
render('dashboard');
